[package]
name = "synthizer"
version = "0.1.0"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
edition = "2018"
license-file = "../LICENSE"

[dependencies]

enum-primitive-derive = "0.2"
log = "0.4"
num-traits = "0.2"
paste = "1"
synthizer-sys = { path = "../synthizer-sys" }
thiserror = "1"