[package]
name = "synthizer"
version = "0.1.0"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
edition = "2018"

[dependencies]

"log" = "0.4"
"synthizer-sys" = { path = "../synthizer-sys" }
"thiserror" = "1"