name: Test

on:
  push:
  pull_request:

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    env:
      LIBCLANG_PATH: C:\Users\runneradmin\scoop\apps\llvm\current\bin
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install llvm ninja
      - run: echo "::add-path::~\scoop\shims"
      - run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features
          cargo check
