name: Test

on:
  push:
  pull_request:

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: echo "::add-path::C:\msys64\mingw64\bin"
      - run: |
          choco install -y llvm cmake ninja
          rustup update
          rustup component add clippy
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features
          echo Find me.
          cmake --version
          clang++ --version
          clang --version
          cargo check
