name: Test

on:
  push:
  pull_request:

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    env:
      CC: C:\ProgramData\chocolatey\bin\clang.exe
      CXX: C:\ProgramData\chocolatey\bin\clang++.exe
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          choco install -y llvm cmake ninja
          rustup update
          rustup component add clippy
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features
          cargo check
